apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    httpscaledobjects.http.keda.sh/version: {{ .Values.version }}
    keda.sh/addon: {{ .Chart.Name }}
    app: {{ .Chart.Name }}
    name: {{ .Chart.Name }}-controller-manager-metrics-service
    app.kubernetes.io/name: {{ .Chart.Name }}-controller-manager-metrics-service
    app.kubernetes.io/version: {{ .Values.version }}
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{ tpl .Values.additionalLabels . | indent 4}}
  name: {{ .Chart.Name }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager
    httpscaledobjects.http.keda.sh/version: {{ .Values.version }}
    keda.sh/addon: {{ .Chart.Name }}
